hwlog/hwlog/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from log import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    #url(r'^login/$', auth_views.login, name = 'login'),
    #url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name = 'logout'),
    url(r'^signup/$', views.signup, name= 'signup'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^configure/$', views.configure, name = 'configure'),
    url(r'^log/', include('log.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^about/', views.about, name = 'about'),
    url(r'^pong/', views.game, name = 'game'),
    url(r'^martor/', include('martor.urls')),
]

hwlog/log/urls.py
from django.conf.urls import url

from . import views

app_name = 'log'
urlpatterns = [
    url(r'^(?P<course_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<course_id>[0-9]+)/history/(?P<page>[0-9]+)$', views.history, name='history'),
    url(r'^reminder/$', views.reminder, name = 'reminder'),
]

hwlog/log/models.py
from martor.models import MartorField
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone

class Reminder(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #hw_text = models.CharField(max_length=180)
    hw_text = MartorField()
    def __str__(self):
        return self.user.username

class Course(models.Model):
    def __str__(self):
        return self.course_name
    #def get_course_name(self):
    #    return str(self.course_name)
    def get_latest_hw(self):
        latest_hw = self.homework_set.latest('pub_date')
        return latest_hw
    course_name = models.CharField(max_length=50)
    students = models.ManyToManyField(User, related_name='courses_joined', blank=True) #creates relationship between the user and course

class Homework(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE,null=True, blank=True)
    #hw_text = models.CharField(max_length=180)
    hw_text = MartorField()
    pub_date = models.DateTimeField('date published')
    poster = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.hw_text

    def was_published_recently(self):
        timenow = timezone.now()
        if ((self.pub_date.weekday()==4 or self.pub_date.weekday()==5) and (timenow.weekday()==5 or timenow.weekday()==6) and (self.pub_date+timedelta(days=3) > timenow)):
            return True #returns true on weekends if hw was posted on friday
        else:
            return self.pub_date.date() == timenow.date()

    def get_pub_date(self):
        return self.pub_date

    def get_poster(self):
        return self.poster

    def get_course(self):
        return self.course
#class Period(models.Model):
#    time = models.IntegerField()
#    hw = models.TextField(max_length=500, blank=True)
#    def __int__(self):
#        return self.time

hwlog/log/forms.py
from django import forms
from .models import Course
#from martor.fields import MartorFormField

class ClassEnrollForm(forms.Form): #form to edit course settings
    courseList = Course.objects.order_by('course_name')

    course_1 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_2 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_3 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_4 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_5 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_6 = forms.ModelChoiceField(queryset=courseList,empty_label=None)
    course_7 = forms.ModelChoiceField(queryset=courseList,empty_label=None)

class ChangeHWForm(forms.Form): #form to edit hw of a class
    hw_text = forms.CharField(widget=forms.Textarea(attrs={'maxlength': '300'}))

hwlog/log/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.views import generic
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
from .models import Course, Homework, Reminder
from .forms import ClassEnrollForm, ChangeHWForm
from django.utils import timezone
from datetime import datetime, timedelta
import math

def about(request):
    return render(request,'about.html')

def home(request): #index page
    return render(request,'index.html')

def signup(request): #signup page
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save() #what does this do
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            Reminder.objects.create(user=user)
            login(request, user)
            return redirect('configure')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def change_password(request): #change password page
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return redirect('home')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form})

def configure(request): #settings page, might be lots of bugs
    if request.method == 'POST':        #what happens if user adds more than 7 courses
        form = ClassEnrollForm(request.POST)
        if form.is_valid():
            request.user.courses_joined.clear()
            coursearray = []
            for x in range(0,7): #adding students to courses
                coursearray.append(form.cleaned_data['course_'+str(x+1)])
                coursearray[x].students.add(request.user)
            return redirect('home')
    else:
        user_courses = request.user.courses_joined.all()
        user_class = [ ]
        no_course = Course.objects.get(course_name='--None--')

        for x in range(0,7): #create an array with user courses^
            if x < len(user_courses):
                user_class.append(user_courses[x])
            else:
                user_class.append(no_course)

        form = ClassEnrollForm(initial={'course_1': user_class[0], #prepopulating with user's settings
                                        'course_2': user_class[1],
                                        'course_3': user_class[2],
                                        'course_4': user_class[3],
                                        'course_5': user_class[4],
                                        'course_6': user_class[5],
                                        'course_7': user_class[6],
                                        })
    return render(request, 'configure.html', {'form': form})

def detail(request, course_id): #page to edit hw
    course = get_object_or_404(Course, pk=course_id)
    if request.method == 'POST':
        form = ChangeHWForm(request.POST)
        if form.is_valid():
            course.homework_set.create(hw_text=form.cleaned_data['hw_text'], pub_date=timezone.now(), poster=request.user)
            return redirect('home')
    else:
        form = ChangeHWForm()

    one_week_ago = timezone.now()-timedelta(days=7) #create date object to filter homework posted within a week
    hw_list = course.homework_set.filter(pub_date__gte=one_week_ago)
    length = len(hw_list)
    if length > 10: end = length-11
    else: end = None #using 0 doesnt work, since it would exclude the last element
    latest_hw_list = hw_list[length:end:-1]
    if len(course.homework_set.all())-1 >= 0: latest_hw = course.homework_set.all()[len(course.homework_set.all())-1]
    else: latest_hw = ""
    return render(request, 'detail.html', {'form': form,
                                            'course_name': course.course_name,
                                            'course_id': course.id,
                                            'latest_hw_list': latest_hw_list,
                                            'latest_hw': latest_hw})

def history(request, course_id, page): #page to view full history
    course = get_object_or_404(Course, pk=course_id)
    full_list = course.homework_set.all()
    length = len(full_list)
    limit = 30 # how many items per page / doesnt work after 40?
    last_page = math.ceil(length/limit)
    page = int(page)
    if page > last_page:
        return redirect('log:history',course_id=course_id, page=last_page)  
    if (length < limit):
        hw_list = full_list[::-1]
    elif (length-page*limit-1 < limit):
        hw_list = full_list[length-(page-1)*limit-1:0:-1] 
    else:
        hw_list = full_list[length-(page-1)*limit-1:length-page*limit-1:-1]
    prev_bool = True
    next_bool = True
    if page==1: prev_bool = False
    if page==last_page: next_bool = False
    return render(request, 'history.html', {'course_name': course.course_name,
                                            'course_id': course.id,
                                            'prev': prev_bool,
                                            'next': next_bool,
                                            'prev_page':page-1,
                                            'next_page':page+1,
                                            'hw_list': hw_list})


def reminder(request): #page to edit remainder
    if request.method == 'POST':
        form = ChangeHWForm(request.POST)
        if form.is_valid():
            request.user.reminder.hw_text=form.cleaned_data['hw_text']
            request.user.reminder.save()
            return redirect('home')
    else:
        form = ChangeHWForm()

    return render(request, 'reminder.html', {'form': form,})

def game(request):
    return render(request, 'pong.html')

hwlog/log/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}

{% block content %}
  <div class="content-container">
    <div class="about-container">
      <p>logof(HW) is an online homework log developed by the SMIC Computer Club for SMIC students.</p>
      <p>It is the product of many months of arduous labor from a student just like you. </p>
      <p>In addition, logof(HW) costs lots of money to maintain.</p>
      <p>Please consider donating if you find this tool useful!</p>
      {% load static %}<img src="{% static 'log/images/paymentQR.jpg' %}" class="QR">
    </div>
  </div>
{% endblock %}

hwlog/log/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'log/style.css' %}" />
  <link rel="stylesheet" href="{% static 'log/stylesheet.css' %}" type="text/css" charset="utf-8" />
  <title>{% block title %}log(HW){% endblock %}</title>
  <meta name='viewport' content='width=device-width, initial-scale=1' />
  <link rel="shortcut icon" href="{% static 'log/images/favicon.ico' %}"/>


  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114028413-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-114028413-1');
  </script>

</head>
<body>
  <div class='wrapper'>
    <header>
      <div class='menu-container'>
        <a href="{% url 'home' %}">{% load static %}<img src= "{% static 'log/images/logo.svg' %}" class='header-logo'/></a>
        <ul class='menu'>
          {% if user.is_authenticated %}
            <li class='hi-message'><strong>{{ user.username }}</strong></li>
            <li class='menu-text'><a href ="{% url 'configure' %}"> Settings </a></li>
            <li class='menu-text'><a href ="{% url 'change_password' %}"> Change password </a></li>
            <li class='menu-text'><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class='menu-text'><a href="{% url 'about' %}">About</a></li>
            <li class='menu-text'><a href="{% url 'signup' %}"> Sign up </a></li>
            <li class='menu-text'><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <div class="push"></div>
  </div>
  <footer>
    <div class="footer-container" style="justify-content: center">
      <p> Made by Danny Yu of the SMIC Computer Club</p>
    </div>
    <div class="footer-container">
      <div style="display:flex; flex-direction: column; align-items: center;">
        <img style="height:100px; width:100px; margin-bottom:10px;" src="{% static 'log/images/SupportGroupQR.jpg' %}" />
        <p>Join the support group!</p>
      </div>
      <p><a href="{% url 'about' %}" class="about-link">About</a></p>
    </div>
  </footer>
</body>
</html>

hwlog/log/templates/change_password.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock %}

{% block content %}
  <div class="content-container">
    {% if user.is_authenticated %}
      <div class = "lgn-container">
        <h1 class="content-heading">Change Password</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn">Save changes</button>
        </form>
      </div>
    {% else %}
    <a href="{% url 'login' %}">Login before you change your password! </a>
    {% endif %}
  </div>
{% endblock %}

hwlog/log/templates/configure.html
{% extends 'base.html' %}
{% block title %}Settings{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <form method="post">
      <div class="content-container">
        <div class="lgn-container">
          <h1 class="content-heading">Select your classes</h2>
          {% csrf_token %}
          {% load widget_tweaks %}
          <div class="configure-row">
            <label for='c1'>Class 1</label>
            <div class="styled-select">
              {% render_field form.course_1 id+="c1" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c2'>Class 2</label>
            <div class="styled-select">
              {% render_field form.course_2 id+="c2" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c3'>Class 3</label>
            <div class="styled-select">
              {% render_field form.course_3 id+="c3" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c4'>Class 4</label>
            <div class="styled-select">
              {% render_field form.course_4 id+="c4" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c5'>Class 5</label>
            <div class="styled-select">
              {% render_field form.course_5 id+="c5" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c6'>Class 6</label>
            <div class="styled-select">
              {% render_field form.course_6 id+="c6" size="2" %}
            </div>
          </div>
          <div class="configure-row">
            <label for='c7'>Class 7</label>
            <div class="styled-select">
              {% render_field form.course_7 id+="c7" size="2" %}
            </div>
          </div>
          <button type="submit" class="btn">Submit</button>
        </div>
      </div>
    </form>
  {% else %}
    <a href="{% url 'login' %}">Login before you can edit! </a>
  {% endif %}
{% endblock %}

hwlog/log/templates/detail.html
{% extends 'base.html' %}
{% block title %}Edit HW{% endblock %}

{% block content %}
  <script>
    function copyLatest(){
      textarea = document.getElementById("txtarea");
      textarea.value = "{{ latest_hw }}"
    }
  </script>
  <div class="content-container">
    <div class="lgn-container detail-container">
      {% if user.is_authenticated %}
        <h1 class="content-heading detail-heading">{{course_name}}</h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            {% load widget_tweaks %}
            {% render_field form.hw_text class+="hw-textarea" id="txtarea" %}
            <div class="js-btn history-link" onclick="copyLatest()">
              Copy from latest
            </div>
          </div>
          
          <button type="submit" class="btn orange">Save changes</button>
        </form>
      {% else %}
        <a href="{% url 'login' %}">Login before you can edit! </a>
      {% endif %}
    </div>
    <h2 style="margin-bottom: 15px"> Previous Homeworks </h2>
    {% for homework in latest_hw_list %}
    <div class="extra-hw-box">
      {% load martortags %}
      {{homework.hw_text|safe_markdown}}
      <div class="date">{{homework.poster}} - {{homework.get_pub_date}}</div>
    </div>
    {% endfor %}
    <a href="{% url 'log:history' course_id=course_id page=1 %}" class="history-link">See full history</a>
  </div>
{% endblock %}

hwlog/log/templates/history.html
{% extends 'base.html' %}
{% block title %}History{% endblock %}

{% block content %}
  <div class="content-container">
    <h2 style="margin-bottom: 15px"> {{course_name}} </h2>
    {% for homework in hw_list %}
    <div class="extra-hw-box">

      <p>
      	{% load martortags %}
      	{{homework.hw_text|safe_markdown}}
      </p>
      <div class="date">{{homework.poster}} - {{homework.get_pub_date}}</div>
    </div>
    {% endfor %}
    <div class="arrow-container">
    	{% if prev %}
    	<a class="arrow" href = "{% url 'log:history' course_id=course_id page=prev_page %}"> < Prev </a>
    	{% else %}
    	<div></div>
    	{% endif %}
    	{% if next %}
    	<a class="arrow" href = "{% url 'log:history' course_id=course_id page=next_page %}"> Next > </a>
    	{% else %}
    	<div></div>
    	{% endif %}
    </div>
  </div>
{% endblock %}

hwlog/log/templates/index.html
{% extends 'base.html' %}
{% block title %}log(HW){% endblock %}

{% block content %}
  <script>
    function strikeThrough(clicked_id){
      element = document.getElementById(clicked_id);
      if (element.style.textDecoration != "line-through"){
        element.style.setProperty("text-decoration", "line-through");
      }
      else{
        element.style.setProperty("text-decoration", "none");
      }
    }
  </script>
  <div class="content-container">
    {% if user.is_authenticated %}
      {% if user.courses_joined.count > 0 %}
        <div class="log-container">
          {% for course in user.courses_joined.all %}
            {% if course.course_name == "--None--" %}
            {% else %}
              <div class="log-container-row">
                <div class="course-name-box">
                  {{course.course_name}}
                  {% if course.get_latest_hw.was_published_recently == False  %}
                    {% load static %}<img src="{% static 'log/images/warning.svg' %}" class="warning-icon" title="Not updated today"/>
                    <div class="warning-text">Not updated today</div>
                  {% endif %}
                  <a href="{% url 'log:detail' course.id %}">
                    {% load static %}<img src="{% static 'log/images/edit-icon.svg' %}" class="edit-icon" title="Edit"/></a>
                </div>
                <div class="hw-box" onclick="strikeThrough(this.id)" id="{{course.id}}">
                  {% load martortags %}
                  {{course.get_latest_hw.hw_text|safe_markdown}}
                  <div class="date">{{course.get_latest_hw.get_pub_date}}</div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
          <div class="log-container-row">
            <div class="course-name-box">
              Personal Reminder
              <a href="{% url 'log:reminder' %}">
                {% load static %}<img src="{% static 'log/images/edit-icon.svg' %}" class="edit-icon" title="Edit"/></a>
            </div>
            <div class="hw-box" onclick="strikeThrough(this.id)" id="{{course.id}}">
              {{user.reminder.hw_text|safe_markdown}}
            </div>
          </div>
        </div>
      {% else %}
        <a href = "{% url 'configure' %}">Please select your classes first!</a>
      {% endif %}
    {% else %}
      <div class="index-top-section">
        <div class="index-container">
          <div class="index-box">
            <span class="index-heading-text">The Modern Homework Log</span>
            <span class="index-banner-text">log(HW) is a platform for students to share and keep track of homework assignments more effectively. </span>
          </div>
          <div class="button-container">
            <figure>
              <a href="{% url 'login' %}">
                <div>
                  <span class="cool-button">Already have an account?</span>
                  <span class="cool-button">Login </span>
                </div>
              </a>
            </figure>
            <figure>
              <a href="{% url 'signup' %}">
                <div>
                  <span class="cool-button">Don't have an account?</span>
                  <span class="cool-button">Sign Up</span>
                </div>
              </a>
            </figure>
          </div>
        </div>
      </div>
      <div class="index-button-container">
        <div class="home-boxes">
          <p class="box-label">Already have an account? </p>
          <a href="{% url 'login' %}" class="button-link"><div class="button-index"> Login </div></a>
        </div>
        <div class="home-boxes">
          <p class="box-label"> Don't have an account? </p>
          <a href="{% url 'signup' %}" class="button-link"><div class="button-index"> Sign up </div></a>
        </div>
      </div>
      <div class="log-container index-description-text" style="margin-top: 30px;">
        It's a common sight to see a student desperately scribble down the homework before hurriedly dashing to the next class. <br>
        Or in other cases, the student might have forgotten to entirely. <br>
        Or perhaps the student is simply too lazy. <br><br>
        Cue log(HW). <br><br>
        log(HW) allows each student to personalize his/her own online homework log.
        Only one person needs to upload the homework, and everyone will be able to see it on their own homework logs. <br>
        log(HW) combines the best of both worlds—it retains the compact format of a traditional homework log, and it is also digitized to facilitate the sharing of homework.

      </div>


    {% endif %}
  </div>
{% endblock content %}

hwlog/log/templates/pong.html
{% extends 'base.html' %}
{% block title %}Pong{% endblock %}

{% block content %}
  <div class="content-container">
  	<canvas id="gameCanvas" width="800" height="600"></canvas>
	<script>
		var canvas;
		var canvasContext;
		var ballX=400;
		var ballY=400;
		var ballSpeedX = 3;
		var origSpeedY = 3;
		var ballSpeedY = origSpeedY;
		var paddle1Y = 250;
		var paddle2Y = 250;
		var acc=0;
		var win_screen = false;
		var start_screen = true;

		const WIN_SCORE = 3;
		const ADJ = 20;
		const PADDLE_HEIGHT = 100;
		const PADDLE_WIDTH = 20;
		const BALL_RADIUS = 10;

		var player1Score = 0;
		var player2Score = 0;

		function calculateMousePos(evt){
			var rect = canvas.getBoundingClientRect();
			var root = document.documentElement;
			var mouseX = evt.clientX - rect.left - root.scrollLeft;
			var mouseY = evt.clientY - rect.top - root.scrollTop;
			return {
				x:mouseX,
				y:mouseY
			}
		}
		function handleMouseClick(evt) {
			if(win_screen) {
				player1Score = 0;
				player2Score = 0;
				win_screen = false;
			}
			else if (start_screen) {
				start_screen = false;
			}
		}
		window.onload = function(){
			canvas = document.getElementById('gameCanvas');
			canvasContext = canvas.getContext('2d');
			canvasContext.font="30px Verdana";
			
			var framesPerSecond = 60;
			setInterval(function(){
					moveEverything();
					drawEverything();
			}, 1000/framesPerSecond);

			canvas.addEventListener('mousemove',
				function(evt) {
					var mousePos = calculateMousePos(evt);
					paddle1Y = mousePos.y-PADDLE_HEIGHT/2;
				});
			canvas.addEventListener('mousedown', handleMouseClick);
		}
		function moveEverything(){
			if (win_screen || start_screen){
				return;
			}

			ballY += ballSpeedY;
			ballX += ballSpeedX;
			twoHundredIQ();
			if (ballX > canvas.width-PADDLE_WIDTH-BALL_RADIUS){
				if (ballY >= paddle2Y - ADJ && ballY <= paddle2Y + PADDLE_HEIGHT + ADJ){
					ballSpeedX *= -1;
					var deltaY = ballY - (paddle2Y+PADDLE_HEIGHT/2);
					ballSpeedY = origSpeedY * (deltaY*0.05);
				}else{
				player1Score++;
				ballReset();
				}
			} 
			if (ballX <PADDLE_WIDTH+BALL_RADIUS){
				if (ballY >= paddle1Y - ADJ && ballY <= paddle1Y + PADDLE_HEIGHT + ADJ){
					ballSpeedX *= -1;
					var deltaY = ballY - (paddle1Y+PADDLE_HEIGHT/2);
					ballSpeedY = origSpeedY * (deltaY*0.05);
				}else{
				player2Score++;
				ballReset();
				}
			}
			if (ballY > canvas.height || ballY <0){
				ballSpeedY *= -1;
			}

		}
		function drawNet() {
			for(var i=0;i<canvas.height;i+=40) {
				colorRect(canvas.width/2-1,10+i,2,20,'white');
			}
		}
		function twoHundredIQ(){
			if (paddle2Y + PADDLE_HEIGHT/2 < ballY){
				paddle2Y += Math.abs(ballSpeedY)*0.86;
			}
			else{
				paddle2Y -= Math.abs(ballSpeedY)*0.86;
			}
		}
		function drawEverything(){
			moveEverything();
			colorRect(0, 0, canvas.width, canvas.height, 'black');
			if (win_screen){
				canvasContext.fillStyle = 'white';
				if (player1Score > player2Score){
					canvasContext.fillText("you won",350,100);
				}
				else{
					canvasContext.fillText("weak",350,100);
				}
				canvasContext.fillText("Click to continue", 200, 400);
				return;
			}
			drawNet();
			colorRect(0, paddle1Y, PADDLE_WIDTH, PADDLE_HEIGHT, 'white');
			colorRect(canvas.width - PADDLE_WIDTH, paddle2Y, PADDLE_WIDTH, PADDLE_HEIGHT, 'white');
			colorCircle(ballX, ballY, BALL_RADIUS, 'white');

			canvasContext.fillText(player1Score, 100, 100);
			canvasContext.fillText(player2Score, 700, 100);

		}
		function ballReset(){
			if (player1Score >= WIN_SCORE || player2Score >= WIN_SCORE){
				win_screen = true;
			}
			ballSpeedX *= -1;
			ballSpeedY = origSpeedY;
			ballX = canvas.width/2;
			ballY = canvas.height/2;
		}
		function colorRect(leftX,topY, width,height, drawColor){
			canvasContext.fillStyle = drawColor;
			canvasContext.fillRect(leftX,topY, width,height);
		}
		function colorCircle(x, y, radius, color){
			canvasContext.fillStyle = color;
			canvasContext.beginPath();
			canvasContext.arc(x, y, radius, 0, Math.PI*2, true);
			canvasContext.fill();
		}
	</script>
  </div>
{% endblock %}

hwlog/log/templates/reminder.html
{% extends 'base.html' %}
{% block title %}Reminder{% endblock %}

{% block content %}
  <div class="content-container">
    <div class="lgn-container detail-container">
      {% if user.is_authenticated %}
        <h1 class="content-heading detail-heading">Reminder</h2>
        <h3 class="content-heading detail-heading">Others will not see this!<h3>
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            {% load widget_tweaks %}
            {% render_field form.hw_text class+="hw-textarea" %}
          </div>
          <button type="submit" class="btn orange">Save changes</button>
        </form>
      {% else %}
        <a href="{% url 'login' %}">Login before you can edit! </a>
      {% endif %}
    </div>
  </div>
{% endblock %}

hwlog/log/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}

{% block content %}
  <div class="content-container">
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout first before creating a new account!</a>
    {% else %}
    <div class = "lgn-container">
      <h1 class="content-heading">Sign up</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Sign up</button>
      </form>
    </div>
    {% endif %}
  </div>
{% endblock %}